<?php

namespace DC3\InstawallBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * QueueRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class QueueRepository extends EntityRepository
{
}
